"""empty message

Revision ID: 64d34f68ba32
Revises: 5ccf602336a0
Create Date: 2018-07-12 22:58:14.365278

"""

# revision identifiers, used by Alembic.
revision = '64d34f68ba32'
down_revision = '5ccf602336a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cosmos_clusters',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verbose_name', sa.String(length=250), nullable=True),
    sa.Column('cluster_name', sa.String(length=250), nullable=True),
    sa.Column('mongo_url', sa.String(length=250), nullable=True),
    sa.Column('metadata_last_refreshed', sa.DateTime(), nullable=True),
    sa.Column('cache_timeout', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_name'),
    sa.UniqueConstraint('verbose_name')
    )
    op.create_table('cosmos_datasources',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_endpoint', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('offset', sa.Integer(), nullable=True),
    sa.Column('cache_timeout', sa.Integer(), nullable=True),
    sa.Column('params', sa.String(length=1000), nullable=True),
    sa.Column('perm', sa.String(length=1000), nullable=True),
    sa.Column('datasource_name', sa.String(length=255), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('filter_select_enabled', sa.Boolean(), nullable=True),
    sa.Column('fetch_values_from', sa.String(length=100), nullable=True),
    sa.Column('cluster_name', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['cluster_name'], [u'cosmos_clusters.cluster_name'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'ab_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasource_name', 'cluster_name')
    )
    op.create_table('cosmos_columns',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('verbose_name', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('groupby', sa.Boolean(), nullable=True),
    sa.Column('count_distinct', sa.Boolean(), nullable=True),
    sa.Column('sum', sa.Boolean(), nullable=True),
    sa.Column('avg', sa.Boolean(), nullable=True),
    sa.Column('max', sa.Boolean(), nullable=True),
    sa.Column('min', sa.Boolean(), nullable=True),
    sa.Column('filterable', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], [u'cosmos_datasources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cosmos_metrics',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('changed_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=512), nullable=True),
    sa.Column('verbose_name', sa.String(length=1024), nullable=True),
    sa.Column('metric_type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('d3format', sa.String(length=128), nullable=True),
    sa.Column('warning_text', sa.Text(), nullable=True),
    sa.Column('datasource_id', sa.Integer(), nullable=True),
    sa.Column('json', sa.Text(), nullable=True),
    sa.Column('changed_by_fk', sa.Integer(), nullable=True),
    sa.Column('created_by_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['created_by_fk'], [u'ab_user.id'], ),
    sa.ForeignKeyConstraint(['datasource_id'], [u'cosmos_datasources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_name', 'datasource_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cosmos_metrics')
    op.drop_table('cosmos_columns')
    op.drop_table('cosmos_datasources')
    op.drop_table('cosmos_clusters')
    # ### end Alembic commands ###
