"""empty message

Revision ID: b2100f98b32e
Revises: 64d34f68ba32
Create Date: 2018-07-31 13:48:27.237771

"""

# revision identifiers, used by Alembic.
revision = 'b2100f98b32e'
down_revision = '64d34f68ba32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cosmos_datasources', sa.Column('main_dttm_col', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cosmos_datasources', 'main_dttm_col')
    # ### end Alembic commands ###
